<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ContractManager.Domain\ContractManager.Domain.csproj" />
  </ItemGroup>
</Project>