<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContractManager.Data\ContractManager.Data.csproj" />
    <ProjectReference Include="..\ContractManager.Domain\ContractManager.Domain.csproj" />
  </ItemGroup>

</Project>
